site_name: ormar
site_description: A simple async ORM with fastapi in mind and pydantic validation.
nav:
  - Overview: index.md
  - Installation: install.md
  - Models:
    - Definition: models/index.md
    - Inheritance: models/inheritance.md
    - Methods: models/methods.md
    - Migrations: models/migrations.md
    - Internals: models/internals.md
  - Fields:
    - Common parameters: fields/common-parameters.md
    - Fields types: fields/field-types.md
    - Pydantic only fields: fields/pydantic-fields.md
    - Fields encryption: fields/encryption.md
  - Relations:
    - relations/index.md
    - relations/postponed-annotations.md
    - relations/foreign-key.md
    - relations/many-to-many.md
    - relations/queryset-proxy.md
  - Queries:
    - queries/index.md
    - queries/create.md
    - queries/read.md
    - queries/update.md
    - queries/delete.md
    - queries/joins-and-subqueries.md
    - queries/filter-and-sort.md
    - queries/select-columns.md
    - queries/pagination-and-rows-number.md
    - queries/aggregations.md
    - Return raw data: queries/raw-data.md
  - Signals: signals.md
  - Transactions: transactions.md
  - Use with Fastapi:
    - Quick Start: fastapi/index.md
    - Using ormar in responses: fastapi/response.md
    - Using ormar in requests: fastapi/requests.md
  - Use with mypy: mypy.md
  - PyCharm plugin: plugin.md
  - Contributing: contributing.md
  - Release Notes: releases.md
  - Api (BETA): api/

repo_name: collerek/ormar
repo_url: https://github.com/collerek/ormar
theme:
  name: material
  highlightjs: true
  hljs_languages:
      - python
  palette:
    primary: indigo
  analytics:
    gtag: G-ZJWZYM5DNM
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
plugins:
- search
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    watch:
      - ormar
    handlers:
      python:
        selection:
          docstring_style: sphinx
        rendering:
          show_submodules: no
extra:
  analytics:
    provider: google
    property:  UA-72514911-3
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
