# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: type_check

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches: [ master, pydantic_v2 ]

jobs:
  lint:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'collerek/ormar'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.4.2
        virtualenvs-create: false

    - name: Poetry details
      run: |
        poetry --version
        poetry config --list

    - name: Install dependencies
      run: poetry install --extras "all" --no-root

    - name: Type check
      run: make type_check
